on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Timestamp
        id: timestamp
        run: echo "timestamp=$(date +%s)" >> $GITHUB_ENV

      - name: Call ZMK Build User Config
        uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
        with:
          archive_name: moop-firmware-${{ env.timestamp }}