on: [push, pull_request, workflow_dispatch]

jobs:
  generate-timestamp:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.get-timestamp.outputs.timestamp }}
    steps:
      - name: Generate Unix Timestamp
        id: get-timestamp
        run: |
          echo "timestamp=$(date +%s)" >> "$GITHUB_OUTPUT"

  build:
    needs: generate-timestamp
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      archive_name: moop-firmware-${{ needs.generate-timestamp.outputs.timestamp }}
